### ISSUE TITLE
v0.18.x fails to build after building v0.17.x

### ISSUE THREAD

**Issue by mceachen** [lovell/sharp#921]
I'm happily using `ridge` versions in my projects across mac, linux, and win10 builds, with and without electron, so from a consumer standpoint, `sharp` is great.

I tried to finish my older PR (failOnError) today, rebased my patch against master, and saw compilation errors during `rm -rf node_modules && npm install` on win10. I switched to the master branch to get to a known-good state, and there were still compilation errors. I tried upgrading npm (to pull in a new `node-gyp`) and `yarn`, but the only way I can get my tree to compile is to revert to a `v0.17.*` tag.

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mrm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mrm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mrm\src\sharp
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by mceachen** [comment]
The solution is to `git clean -fdx`. `npm run clean` doesn't remove the `lib` or `include` directories. Would you like a PR that adds that?

**Comment by mceachen** [comment]
Also, just want to reiterate that sharp is 👌. 👍!

**Comment by lovell** [comment]
Hi Matthew, sorry you ran into this, I think it should only impact those working on the source between 0.17.x and 0.18.x. Given `lib` is now a valid directory containing the JS code, I'm not sure the proposed change is the right thing to do.

(At some point the the `vendor` directory will either become platform-specific or the installation script will check the contents of `vendor` matches the current platform.)

**Comment by mceachen** [comment]
OK, closing.
