### ISSUE TITLE
Sharp breaks on Ubuntu 18.04

### ISSUE THREAD

**Issue by meesrutten** [lovell/sharp#1373]
I have a droplet on Digital Ocean which runs Ubuntu 18.04.
Before this I was using Sharp on a server with Ubuntu 17.04 where it worked correctly.
Now on my droplet it doesn't work and I receive this error:

```javascript
Error: Cannot find module '../build/Release/sharp.node'
1|scheepva |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
1|scheepva |     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
1|scheepva |     at Module.require (internal/modules/cjs/loader.js:598:17)
1|scheepva |     at require (internal/modules/cjs/helpers.js:11:18)
1|scheepva |     at Object.<anonymous> (/var/www/html/dev.verhalenvanger-hetscheepvaartmuseum/node_modules/sharp/lib/constructor.js:10:15)
1|scheepva |     at Module._compile (internal/modules/cjs/loader.js:654:30)
1|scheepva |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
1|scheepva |     at Module.load (internal/modules/cjs/loader.js:566:32)
1|scheepva |     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
1|scheepva |     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
1|scheepva |     at Module.require (internal/modules/cjs/loader.js:598:17)
1|scheepva |     at require (internal/modules/cjs/helpers.js:11:18)
1|scheepva |     at Object.<anonymous> (/var/www/html/dev.verhalenvanger-hetscheepvaartmuseum/node_modules/sharp/lib/index.js:3:15)
1|scheepva |     at Module._compile (internal/modules/cjs/loader.js:654:30)
1|scheepva |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
1|scheepva |     at Module.load (internal/modules/cjs/loader.js:566:32)
```

`1|scheepva |` comes from PM2 which keeps my Node.js running.

Are you guys working on support for Ubuntu 18.04 or is there something I can do to fix this error?

**Comment by lovell** [comment]
Hello, sharp works fine on Ubuntu 18.04. If `build/Release/sharp.node` is missing then something probably went wrong during `npm install`.

**Comment by lovell** [comment]
Feel free to re-open with more information if this problem remains.

**Comment by Crazie-ash** [comment]
I am using sharp v0.23.0 & libvips v0.0.2 with an electron app. It works fine in development mode... But came negative after taking build.... Once the code reaches sharp implemented method, my app crashes automatically. Later, I got to know that it is not supported with ubuntu 18.04. Whereas, other in other platforms like windows & mac it works fine.... 

Is there any solution for this issue?

**Comment by lovell** [comment]
@Crazie-ash The "libvips" package published to npm is completely unrelated to sharp or libvips so can be removed from your dependencies.
