### PR TITLE
Fix testsuite for upcoming libvips v8.13.0

### PR DESCRIPTION
**Pull request by kleisauke**
**Upgrade to libvips v8.13.0-rc1**

- Update libvips C++ sources to v8.13.0-rc1.
- Regenerate expected fixtures.
- Switch from `decompress-zip` to `extract-zip` (the former seems to hang when unzipping a ZIP64 file that uses
the general purpose bit flag 3 as file entry).
- Rework `options.create` so that it is compatible with the revised interpretation guesser (see commit https://github.com/libvips/libvips/commit/57cd94278a245785e840634b3600fae8cfc4d244).
- Remove redudant `g_setenv("VIPS_MIN_STACK_SIZE", "2m", FALSE);` (see commit https://github.com/libvips/libvips/commit/43db3985d0c0f0321434f2bd1cda36c7dd4fa1e5).
- Fix `test/unit/metadata.js` to take new libnsgif loop behavior into account (see commit https://github.com/libvips/libvips/commit/292ee9a47e86c12e07be35aacf75dcaf721f2f98).
- Fix `test/unit/tile.js` to take `vips-properties.xml` into account (see commit https://github.com/libvips/libvips/commit/39e75e07a227169d9c53f910f32c395e6992a5fa).
- Fix `test/unit/avif.js` for new resize behavior (see commit https://github.com/libvips/libvips/commit/894ed1cb135e72a81043b595e37c6e39f5e35cc8).

### CODE REVIEW

**Comment by jcupitt** [comment]
> it seems that rsvg_handle_get_intrinsic_size_in_pixels returns FALSE on SVG images without a viewbox

I put in code for that, but I wasn't expecting rsvg_handle_get_intrinsic_size_in_pixels() to assign the size if there's no viewbox, groan. I'll fix it, thanks for pointing it out.

**Comment by jcupitt** [comment]
The SVG issue should be fixed in libvips master.

**Comment by lovell** [comment]
Thanks Kleis, I'm away at the moment with limited Internet access, will take a look at the weekend.

**Comment by kleisauke** [comment]
With PR https://github.com/libvips/libvips/pull/2817 it almost passes the test suite. Remaining failures:
```
  1) Tile
       Write to ZIP container using file extension:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/kleisauke/sharp/test/unit/tile.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  2) Tile
       Write to ZIP container using container tile option:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/kleisauke/sharp/test/unit/tile.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```
It looks like reverting commit https://github.com/libvips/libvips/commit/a9d64bea54c1fba083a9907c66e19333416a0d7e locally would fix that.

**Comment by kleisauke** [comment]
I could fix the remaining failures with commit 5b1ee32cd4d538911fb2b907d87cdaca7f6dbf93. `decompress-zip` seems to hang when unzipping a ZIP64 file that uses the general purpose bit flag 3 as file entry.
```bash
# libvips 8.12.2 
$ zipdetails test/fixtures/output.dz.container.zip 2> /dev/null | grep -A3 "Zip Spec" | head -4
00004 Extract Zip Spec      14 '2.0'
00005 Extract OS            00 'MS-DOS'
00006 General Purpose Flag  0000
00008 Compression Method    0000 'Stored'
# libvips 8.13.0
$ zipdetails test/fixtures/output.dz.container.zip 2> /dev/null | grep -A4 "Zip Spec" | head -5
00004 Extract Zip Spec      2D '4.5'
00005 Extract OS            00 'MS-DOS'
00006 General Purpose Flag  0008
      [Bit  3]              1 'Streamed'
00008 Compression Method    0000 'Stored'
```

**Comment by kleisauke** [comment]
I've clarified the `test/unit/avif.js` changes with commit 5e8ffa9eb8ef6c2a1cd29b8d95bb848ffffe2380. This is ready for review now.

**Comment by kleisauke** [comment]
Commit f755a5aca166bbae44342f1c7c4ead9606c7c88f updates the pre-built libvips binaries to https://github.com/lovell/sharp-libvips/releases/tag/v8.13.0-rc1. The testsuite passes locally when doing:
```bash
SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --build-from-source && npm test
```

**Comment by kleisauke** [comment]
Prior to commit 7767e0743ce115aab6f42043ae26b9c7adc05131, the Windows build failed with:
```
fatal error C1189: #error:  You must define GETTEXT_PACKAGE before including gi18n-lib.h.  Did you forget to include config.h? (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [D:\a\sharp\sharp\build\libvips-cpp.vcxproj]
```
This was introduced in PR https://github.com/libvips/libvips/pull/2695, perhaps we should guard the `#include <glib/gi18n-lib.h>` with `#ifdef HAVE_CONFIG_H`? For example:
```diff
 #ifdef HAVE_CONFIG_H
 #include <config.h>
-#endif /*HAVE_CONFIG_H*/
 #include <glib/gi18n-lib.h>
+#endif /*HAVE_CONFIG_H*/
```

(unfortunately, that will touch a lot of files again)

**Comment by jcupitt** [comment]
Sure, happy to add the guard. I think we'll need rc2 anyway :( argh.

**Comment by jcupitt** [comment]
... that's quite a big PR :/

Do you think the changes are reasonable, or are there breaking things we should fix in libvips?

**Comment by kleisauke** [comment]
Perhaps the M1 Mac Mini is testing the C path of resize? If so, we might see the side effects of https://github.com/libvips/libvips/discussions/2047.

I just regenerated `embed-lab-into-rgba.png` and `flatten-orange.jpg` with this patch:
<details>
  <summary>Patch</summary>

```diff
--- a/test/unit/alpha.js
+++ b/test/unit/alpha.js
@@ -23,11 +23,11 @@ describe('Alpha transparency', function () {
       .flatten({
         background: { r: 255, g: 102, b: 0 }
       })
-      .toBuffer(function (err, data, info) {
+      .toFile(fixtures.expected('flatten-orange.jpg'), function (err, info) {
         if (err) throw err;
         assert.strictEqual(400, info.width);
         assert.strictEqual(300, info.height);
-        fixtures.assertSimilar(fixtures.expected('flatten-orange.jpg'), data, done);
+        done();
       });
   });
 
--- a/test/unit/resize-contain.js
+++ b/test/unit/resize-contain.js
@@ -123,14 +123,13 @@ describe('Resize fit=contain', function () {
         background: { r: 255, g: 102, b: 0, alpha: 0.5 }
       })
       .png()
-      .toBuffer(function (err, data, info) {
+      .toFile(fixtures.expected('embed-lab-into-rgba.png'), function (err, info) {
         if (err) throw err;
-        assert.strictEqual(true, data.length > 0);
         assert.strictEqual('png', info.format);
         assert.strictEqual(64, info.width);
         assert.strictEqual(128, info.height);
         assert.strictEqual(4, info.channels);
-        fixtures.assertSimilar(fixtures.expected('embed-lab-into-rgba.png'), data, done);
+        done();
       });
   });
 
```
</details>

And ran:
```
G_DEBUG=1 npm test
```

The `G_DEBUG=1` env is to ensure libvips will not use the orc path for resize.
https://github.com/lovell/sharp/blob/e40a881ab4a5e7b0e37ba17e31b3b186aef8cbf6/test/unit/beforeEach.js#L8
(perhaps that condition should also check for `VIPS_NOVECTOR`?)

**Comment by kleisauke** [comment]
> Do you think the changes are reasonable, or are there breaking things we should fix in libvips?

I think it's reasonable, I've clarified the changes in the starting post of this PR.

**Comment by lovell** [comment]
@kleisauke Dankjewel, I've merged this into a new `eagle` WIP branch for inclusion in sharp v0.31.0.
