### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by DullReferenceException** [lovell/sharp#19]
I'd like to be able to use sharp on the Windows platform. Because `libvips` is available for Windows, I assume that lack of support is mostly in figuring out the build script.

Has this been investigated already? If so, what approaches have already been tried and roadblocks encountered? Knowing what's been tried so far, if anything, will help me or other potential developers come to a working solution quicker.

**Comment by lovell** [comment]
@michaeldrotar I think you may be experiencing a different problem to @blowsie as you're not seeing the `'true' is not recognized as an internal or external command...` error. It might be that the `which` executable is not found/available on your system.

The `which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONFIG_LIBDIR` part of PKG_CONFIG_PATH is applicable for Macs only. We need to work out a portable way of making Windows ignore any error it generates, like the `|| true` command does for Linux.

I now have in my possession a new Windows 8.1 laptop so hope to make a bit more progress with this. Please do keep adding comments to this issue about your own attempts of getting it working as these all help narrow down the problems.

(On a multi-platform note, I managed to get libvips and sharp working on an ARMv6 Raspberry Pi over Christmas. WebP support was the trickiest bit to get working.)

**Comment by Karnith** [comment]
+1
Would be great to get this working!

**Comment by connor4312** [comment]
:+1: would love to move from gm to Sharp for actual good streaming support :D

**Comment by mrmuh** [comment]
+1 :)

**Comment by blowsie** [comment]
>@blowsie Please can you try changing || true to || exit 0 on line 12 of binding.gyp.

How do I go about doing this when I'm running `npm install`? The files don't exist.

**Comment by lovell** [comment]
@blowsie Thanks for the reply. You'll need to fork your own copy of the sharp repo, clone it locally then make the change. You should then be able to run `npm install` inside the cloned repo to prove it works before committing the change and pushing back to Github.

**Comment by blowsie** [comment]
@lovell thanks!

Unfortunately I get a similar error

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

D:\Projects\github\sharp>npm install
\
> sharp@0.9.3 install D:\Projects\github\sharp
> node-gyp rebuild


D:\Projects\github\sharp>if not defined npm_config_node_gyp (node "C:\Program Fi
les (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\
bin\node-gyp.js" rebuild )  else (rebuild)
The system cannot find the path specified.
gyp: Call to 'which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONF
IG_LIBDIR || exit 0' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_
modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\github\sharp
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! sharp@0.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.9.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\github\sharp\npm-debug.log

```

**Comment by lovell** [comment]
Thanks @blowsie it looks like you and @michaeldrotar are now experiencing a consistent error.

I suspect it's the (lack of) `which` command that's causing the problem now.

Are you able to change `which brew ...` to `where brew ...` at the start of that command? (This will break Mac/Linux compatibility so this change is only to discover what the next wall we'll hit on Windows is.)

**Comment by blowsie** [comment]
Sure, here we go..

After a thorough reading of the comments It seems this variable issue is just the tip of the iceberg.

``
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

D:\Projects\github\sharp>npm install

> sharp@0.9.3 install D:\Projects\github\sharp
> node-gyp rebuild


D:\Projects\github\sharp>if not defined npm_config_node_gyp (node "C:\Program Fi
les (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\
bin\node-gyp.js" rebuild )  else (rebuild)
The system cannot find the path specified.
gyp: Call to 'where brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONF
IG_LIBDIR || exit 0' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_
modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\github\sharp
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! sharp@0.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.9.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\github\sharp\npm-debug.log

D:\Projects\github\sharp>
```

**Comment by connor4312** [comment]
Perhaps moving to a Python build script would work better. Python is required for gyp, so users will have it, and you can do some more intelligent platform-specific handling as needed there...

**Comment by lovell** [comment]
@connor4312 Great suggestion, thank you. I often look for excuses to use Python so not sure why that hasn't come up as an idea before.

**Comment by lovell** [comment]
@blowsie thanks for persisting. I'm typing this on a Windows machine whilst waiting for Visual Studio to install and hope to make some progress with this over the Easter weekend.

**Comment by connor4312** [comment]
I'm not a C/++'er, but I'm pretty competent with Python; if there's anything in particular I can help out with getting builds working, let me know. Still would love to be able to move our application over to Sharp :)

**Comment by lovell** [comment]
I've made some progress with this. With a couple of code and config changes I can get sharp to *compile* on a Windows 8 machine using MSVC via a simple `npm install` but it's failing at *link* time.

The problem I've hit is that the [Windows dist of vips-dev](http://www.vips.ecs.soton.ac.uk/supported/current/win32/) provides the import library as a `.dll.a` file, suitable for GCC. What MSVC needs is ideally a `.lib` or at a minimum a `.def` file (Visual Studio's `lib.exe` tool can reverse-engineer a `.lib` from a `.def`).

@jcupitt Are you able to generate and therefore provide a `libvips.def` file in the distribution? http://www.mingw.org/wiki/msvc_and_mingw_dlls suggests it can be extracted via GCC's `--output-def` flag.

**Comment by lovell** [comment]
I was wrong - it looks like the MSVC linker can handle `.a` import libraries. The problem is that it expects 64 bit libraries by default despite compiling everything for 32 bit.

The `npm_config_arch` environment variable `set npm_config_arch=ia32` ensures node-gyp generates a `vcxproj` file set up for 32 bit linking, so we're past this hurdle.

Next update in a couple of days...

**Comment by lovell** [comment]
The "judgement" branch of sharp (the forthcoming v0.10.0 release) now compiles, links and most importantly works with the 32-bit x86 version of Node.js and io.js on Windows. (I can't get the 64-bit versions to work; that's a problem for another day.)

Please follow the pre-install instructions at https://github.com/lovell/sharp/tree/judgement#windows then install via:
```sh
npm install lovell/sharp#judgement
```

For `node-gyp` to work on Windows you'll need Python 2.7.3 and Microsoft Visual Studio C++ 2013 installed.

For those wanting more detail of the solution, the code changes are in https://github.com/lovell/sharp/commit/ce6813329b30f58fa6547c81f3839472fdaeb8e7 and the config changes are in https://github.com/lovell/sharp/commit/f1ad1216cafcc648ccf570419a788e0e4b9ff0ad

A big thank you for all your help and contributions to this issue over the last 12 months!

**Comment by blowsie** [comment]
Great news, I look forward to testing!

**Comment by mvictoras** [comment]
Lovely! Worked for me, had to "force 32bit" by running npm install --arch=ia32.

**Comment by lovell** [comment]
@mvictoras Was the use of `--arch=ia32` required using the 32 or 64-bit version of Node.js?

**Comment by mvictoras** [comment]
The 32-bit version.

On Wed, Apr 15, 2015 at 12:36 PM, Lovell Fuller <notifications@github.com>
wrote:

> @mvictoras <https://github.com/mvictoras> Was the use of --arch=ia32
> required using the 32 or 64-bit version of Node.js?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lovell/sharp/issues/19#issuecomment-93494915>.
>



-- 
*Victor Mateevitsi*
PhD Candidate - University of Illinois at Chicago <http://www.uic.edu/>
Research Assistant - Electronic Visualization Laboratory
<http://www.evl.uic.edu/>
mvictoras@gmail.com
www <http://www.vmateevitsi.com> | LinkedIn
<http://www.linkedin.com/pub/5/919/845> | Twitter
<http://twitter.com/mvictoras> | UIC <http://www.uic.edu> | EVL
<http://www.evl.uic.edu>

**Comment by Trixt0r** [comment]
I get the following error when I try to build sharp on a win32 platform (environment variables are set correctly):

`resize.obj : error LNK2001: unresolved external symbol _vips__image_sizeof_bandformat [C:\Users\trixt\dropclient\app\node_modules\dropclient-image\node_modules\sharp\build\sharp.vcxproj]
C:\Users\trixt\dropclient\app\node_modules\dropclient-image\node_modules\sharp\build\Release\sharp.node : fatal error LNK1120: 1 unresolved externals [C:\Users\trixt\dropclient\app\node_modules\
dropclient-image\node_modules\sharp\build\sharp.vcxproj]`

The build process worked last Friday... I am building the 32 bit Version on Win 10 x64 TP.

-Trixt0r

**Comment by lovell** [comment]
@Trixt0r The `error LNK2001: unresolved external symbol` looks like a 32 vs 64 bit thing, especially as [vips__image_sizeof_bandformat](https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/header.c#L173) uses 64 bit integers (a "long long" in Windows parlance). Have you tried @mvictoras' suggestion of the `--arch=ia32` flag with npm?

> "The build process worked last Friday"

Does this mean that you had everything working but now it's not? If so, what has changed, e.g. new commits on sharp's judgement branch since commit x?

**Comment by Trixt0r** [comment]
The `--arch=ia32` flag doesn't change anything.
My edit shows, which commit works and which not.
Thanks for the fast reply!

**Comment by lovell** [comment]
@Trixt0r Thank you for narrowing it to a single commit. I can reproduce this problem, which I believe is related to the use of `vips_linear1` introduced in dce36e0.

I notice `vips__image_sizeof_bandformat` was removed in commit https://github.com/jcupitt/libvips/commit/7495690cd6cf387c76a6043897bbbf765a0dc846 earlier today. @jcupitt was this coincidence or in response to this discussion?

**Comment by jcupitt** [comment]
@lovell yes, I noticed the references to vips__image_sizeof_bandformat and remembered that external variables like that were bad in DLLs. I swapped it for a function call: it should be safer and easier to maintain. The array is still there for compatibility. 

vips8 will be frozen very, very soon (I hope, anyway) so it's good to knock warts like this out before that happens.

**Comment by lovell** [comment]
Thanks John.

There's probably an option to allow the MS C++ linker to work with C variables in DLLs but I don't know MSVC well enough. Can anyone help?

What I can do for now is temporarily wrap the new `normalise` code in `#ifndef _WIN32` to hide it from the linker.

**Comment by jcupitt** [comment]
It used to be the case that DLLs just did not support external variables, only external functions. 

DLLs worked like this: a set of stubs would be added to the calling object, one for each entry point in the DLL. Each stub was initialised with a JMP to linking code. At runtime, if execution hit one of these things, it would trigger the linking routine to load the DLL into memory, if it wasn't already loaded, then to search it for the target function, and then to modify the stub to be a direct jump to the target. This is straightforward to implement and means there's no need for a full run-time linker, as you find on *nixes. The downside is that it can only support simple forward linking of function calls; you can't link external variables, and you can't do things like back linking. 

Perhaps the situation has improved since I last looked at this.

**Comment by jcupitt** [comment]
I had a quick look at the normalise function, it looks nice. 

You could make it a bit more concise with `vips_object_local_array()`, I expect you know. For example (untested):

```
        VipsImage **t = (VipsImage **) vips_object_local_array(hook, 7);

        // normalize the luminance band in LAB space:
        if (vips_colourspace(image, &t[0], VIPS_INTERPRETATION_LAB, NULL) ||
                vips_extract_band(t[0], &t[1], 0, "n", 1, NULL) ||
                vips_extract_band(t[0], &t[2], 1, "n", 2, NULL) ||
                vips_stats(t[1], &t[3], NULL)) {
                return Error();
        }

        double min = *VIPS_MATRIX(stats, 0, 0);
        double max = *VIPS_MATRIX(stats, 1, 0);

        if (min == max) {
                // Range of zero: create black image
                if (vips_black(&t[4], image->Xsize, image->Ysize, 
                        "bands", 1, NULL )) {
                        return Error();
                }
        } else {
                double f = 100.0 / (max - min);
                double a = -(min * f);

                if (vips_linear1(t[1], &t[5], f, a, NULL) ||
                        vips_bandjoin2(t[5], t[2], &t[6], NULL) ||
                        vips_colourspace(t[6], &t[4], image->Type, NULL)) {
                        return Error();
                }
         }

        VipsImage *normalized = t[4];
```

You could also consider taking a histogram of L* and setting the range to 1% and 99%, ie. letting the top 1% and the bottom 1% over- and under-expose. This would make it less sensitive to noise and probably produce a more pleasing image in more cases. 

`vips_percent()` does almost this, you'd swap your vips_stats() for this code:

https://github.com/jcupitt/libvips/blob/master/libvips/histogram/percent.c#L82

**Comment by lovell** [comment]
The `judgement` branch should be working on Windows again and I've added a Windows CI job via AppVeyor e.g. https://ci.appveyor.com/project/lovell/sharp/build/19

@jcupitt The use of vips_object_local and vips_object_local_array will go away with #152. Your suggested improvements for normalisation are in #200, thank you.

**Comment by jcupitt** [comment]
Ah great ... yes, #152 should be a nice improvement to readability.

**Comment by lovell** [comment]
Support for Windows now in git master - will be published to npm shortly.

**Comment by lovell** [comment]
Support for Windows now available in v0.10.0 via npm https://www.npmjs.com/package/sharp

Thanks for everyone's help with this year-long task!

Please create a new issue for any problems/improvements you discover.

**Comment by blowsie** [comment]
Great news! thanks everyone and @lovell  :+1:

**Comment by blowsie** [comment]
Sadly, Following the installation instructions on the readme, I get the following error

Windows: 8.1
Node : 0.12.2 (x86)
Npm: 2.7.4
Node-gyp: 1.0.3
Vips: 8.0.2

```
D:\Projects\myproject>npm install sharp
|
> sharp@0.10.0 install D:\Projects\myproject\node_modules\sharp
> node-gyp rebuild


D:\Projects\myproject\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node
_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  common.cc
  utilities.cc
  metadata.cc
  resize.cc
  sharp.cc
..\src\metadata.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [D:\Projects\myproject\node_modules\sharp\build\
sharp.vcxproj]
..\src\sharp.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [D:\Projects\myproject\node_modules\sharp\build\sha
rp.vcxproj]
..\src\utilities.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [D:\Projects\myproject\node_modules\sharp\build
\sharp.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify 
/EHsc (..\src\common.cc) [D:\Projects\myproject\node_modules\sharp\build\sharp.vcxproj]
..\src\resize.cc(6): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [D:\Projects\myproject\node_modules\sharp\build\sh
arp.vcxproj]
..\src\common.cc(3): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [D:\Projects\myproject\node_modules\sharp\build\sh
arp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\myproject\node_modules\sharp
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sharp"

```

**Comment by lovell** [comment]
@blowsie Is [VIPS_HOME](https://github.com/lovell/sharp#windows) set? Does the [$(VIPS_HOME)/include](https://github.com/lovell/sharp/blob/master/binding.gyp#L38) directory exist?

**Comment by blowsie** [comment]
Thanks @lovell, I did have them set, but you prompted me to restart, which did the trick. Maybe I should know by now to restart after setting variables, or maybe it should be added to the readme. :)

**Comment by lovell** [comment]
The `look` work-in-progress branch now supports the installation of sharp on Windows without having to manually download/unpack vips-dev and without having to set/modify any environment variables.

To test it, run `npm install lovell/sharp#look` - please report any problems at #42.

**Comment by blowsie** [comment]
@lovell ooo, nice work! 

Thanks

**Comment by lovell** [comment]
As well as ease-of-installation, it looks like support for 64-bit node.exe on Windows will also be arriving in the next release v0.12.0.

What problems, if any, would anyone who has contributed here have with sharp dropping support for 32-bit Windows from that version onwards?

**Comment by blowsie** [comment]
On v0.12.0 , I'm have proxy issues with the request to `dl.bintray.com` I can only assume it is not npm that is making the request, because npm is proxy configurable and is working fine for everything else for me.

Any ideas how I can get around this ? What is making the request to `dl.bintray.com` ?

**Comment by lovell** [comment]
@blowsie The `request` module is used for this purpose. It supports some fairly common proxy-related environment variables - see https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

Are you setting npm's [https-proxy](https://docs.npmjs.com/misc/config#https-proxy) setting? If so, this might be available at install time for us to manually pass along to the request module, but I'd need to check.

**Comment by blowsie** [comment]
Yep My .npmrc file looks something like this.

```
proxy=http://proxy.com:43128/
https-proxy=http://proxy.com:43128/
```

**Comment by blowsie** [comment]
Setting the environment variables, and restarting the machine did not work for me :(.
It did manage to break a whole plethora of other (Office 365) applications though.

Perhaps using the npm config for this is not such a bad idea.

**Comment by lovell** [comment]
> "It did manage to break a whole plethora of other (Office 365) applications though."

http://thenextweb.com/microsoft/2015/12/03/office-365-is-down-for-many-users-in-europe/ suggests we might not be able to take the credit for that.

> "Perhaps using the npm config for this is not such a bad idea."

Will take a look, thanks for confirming.

**Comment by blowsie** [comment]
**Update**: using the environment variables did infact work, the reason the installation still did not work was because the file at `dl.bintray.com` was actually redirecting to `cloudfront.net`.

So using the environment variables does actually fix the problem, but may effect other applications, like "Skype for Business" in my case

**Comment by lovell** [comment]
@blowsie Commit 16e0d54 should allow for the use of the `https-proxy` setting of `.npmrc`, if any. You can test via `npm install lovell/sharp`.

**Comment by blowsie** [comment]
@lovell  Works a charm thank you very much. I look forward to the next release.

**Comment by lovell** [comment]
@blowsie Great, thanks for confirming.

**Comment by lovell** [comment]
@blowsie v0.12.1 now available via npm
