### ISSUE TITLE
(Re)building with Electron doesn't use npm to set libvips version via env var, generates 404

### ISSUE THREAD

**Issue by nouh** [lovell/sharp#412]
ERROR: https://dl.bintray.com/lovell/sharp/libvips--win.tar.gz status code 404
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

**Comment by lovell** [comment]
Hello, it looks like the libvips version number is missing from the URL. NPM should be setting the [npm_package_config_libvips](https://github.com/lovell/sharp/blob/master/binding.js#L78) environment variable to do this, which is defined [here](https://github.com/lovell/sharp/blob/master/package.json#L76).

How are you installing sharp? Which version of npm?

**Comment by nouh** [comment]
I just put sharp in my package.json, and I use node 4.4.3 and npm 2.15.1

**Comment by nouh** [comment]
when I run npm install , I should set npm_package_config_libvips to some value ?

**Comment by nouh** [comment]
actually, I am using sharp on a electron project.  according to doc, on windows, `npm install` will download the prebuilt binary for me, however I can't find it somewhere.

**Comment by lovell** [comment]
I think this problem arises because `node-gyp rebuild` is triggered outside npm's control when using Electron, and therefore the environment variable is not set.

Which, if any, of the "ways" referred to in https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#how-to-install-native-modules are you using?

**Comment by nouh** [comment]
I use another set nodejs environment for testing. this time I am using node v5.10.1 and npm 3.8.3 . I run  `npm install` with no problem. but when I run `eletron main.js` . Got this Error: Cannot find module './build/Release/sharp'. it seems to me `npm install` did not download the prebuilt binary at all this time.

**Comment by nouh** [comment]
yes, I put electron-rebuild on devDependencies.  but I hadn't run anything after `npm install`

**Comment by lovell** [comment]
Others have [reported unexpected behaviour](https://github.com/lovell/sharp/issues/383#issuecomment-201591783) with electron-rebuild. I'll see if I can get the gyp-based logic to work independently of npm for Electron users.

**Comment by lovell** [comment]
Commit cb10f9a should allow a gyp-based rebuild to function without any npm involvement. Are you able to test the `master` branch of sharp with Electron?

**Comment by nouh** [comment]
thx, I will test it

**Comment by homerjam** [comment]
@nouh could you let us know the results of your tests when you have a chance?

I'd be interested to know more about your electron project if you wouldn't mind sharing? Thanks

**Comment by lovell** [comment]
Closing this issue as I think it should all be working now. Feel free to re-open if not.
